# Generated by Django 4.2.2 on 2023-08-17 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='distance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='latitude',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='longitude',
            field=models.IntegerField(),
        ),
    ]
