# Generated by Django 4.2.2 on 2023-08-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_demo', '0002_alter_user_distance_alter_user_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='distance',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='estimate_time',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
