# Generated by Django 4.2.2 on 2023-08-17 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_demo', '0003_alter_user_distance_alter_user_estimate_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='user',
            name='estimate_time',
        ),
    ]
